Repository SAP/terraform-provider-scc, pull requests merged in 2025-08, with the labels that each got.

#102 chore: prep release v0.2.0-beta1
  docs/index.md
  examples/provider/provider.tf
Labels: ignore-for-release, internal

#104 fix: Improved documentation for certificate
  docs/index.md
  scc/provider/provider.go
Labels: bug, documentation

#108 fix: Aligning attributes for System Mapping Resource
  docs/data-sources/system_mapping_resource.md
  docs/data-sources/system_mapping_resources.md
  docs/resources/system_mapping_resource.md
  examples/resources/scc_system_mapping_resource/import.sh
  examples/resources/scc_system_mapping_resource/resource.tf
  integration/main.tf
  internal/api/apiObjects/types_system_mapping_resource.go
  scc/provider/datasource_system_mapping_resource.go
  scc/provider/datasource_system_mapping_resource_test.go
  scc/provider/datasource_system_mapping_resources.go
  scc/provider/datasource_system_mapping_resources_test.go
  scc/provider/fixtures/datasource_system_mapping_resource.yaml
  scc/provider/fixtures/datasource_system_mapping_resources.yaml
  scc/provider/fixtures/resource_system_mapping_resource.yaml
  scc/provider/resource_system_mapping_resource.go
  scc/provider/resource_system_mapping_resource_test.go
  scc/provider/type_system_mapping_resource.go
Labels: bug, enhancement, breaking-change, test setup

#113 feat: Auto Synchronize Trust Configurations of Subaccount
  internal/api/apiObjects/types_system_mapping.go
  scc/provider/fixtures/resource_subaccount.yaml
  scc/provider/fixtures/resource_subaccount_update.yaml
  scc/provider/fixtures/resource_subaccount_update_tunnel.yaml
  scc/provider/fixtures/resource_subaccount_using_auth.yaml
  scc/provider/fixtures/resource_subaccount_using_auth_update.yaml
  scc/provider/fixtures/resource_subaccount_using_auth_update_tunnel.yaml
  scc/provider/resource_subaccount.go
  scc/provider/resource_subaccount_using_auth.go
  scc/provider/resource_system_mapping_resource_test.go
  scc/provider/type_system_mapping.go
Labels: enhancement

#119 chore: prep release v0.3.0-beta1
  docs/index.md
  examples/provider/provider.tf
Labels: ignore-for-release, internal, new-release

#121 fix: Added Validators for System Mapping Resource
  docs/data-sources/system_mapping.md
  docs/data-sources/system_mappings.md
  docs/resources/subaccount.md
  docs/resources/subaccount_using_auth.md
  docs/resources/system_mapping.md
  internal/api/apiObjects/types_system_mapping.go
  scc/provider/datasource_system_mapping.go
  scc/provider/datasource_system_mappings.go
  scc/provider/fixtures/datasource_system_mapping.yaml
  scc/provider/fixtures/datasource_system_mappings.yaml
  scc/provider/fixtures/resource_subaccount.yaml
  scc/provider/fixtures/resource_subaccount_update.yaml
  scc/provider/fixtures/resource_subaccount_update_tunnel.yaml
  scc/provider/fixtures/resource_subaccount_using_auth.yaml
  scc/provider/fixtures/resource_subaccount_using_auth_update.yaml
  scc/provider/fixtures/resource_subaccount_using_auth_update_tunnel.yaml
  scc/provider/fixtures/resource_system_mapping.yaml
  scc/provider/helper.go
  scc/provider/resource_domain_mapping.go
  scc/provider/resource_subaccount.go
  scc/provider/resource_subaccount_abap_service_channel.go
  scc/provider/resource_subaccount_k8s_service_channel.go
  scc/provider/resource_subaccount_test.go
  scc/provider/resource_subaccount_using_auth.go
  scc/provider/resource_subaccount_using_auth_test.go
  scc/provider/resource_system_mapping.go
  scc/provider/resource_system_mapping_resource.go
  scc/provider/resource_system_mapping_test.go
  scc/provider/type_system_mapping.go
  validation/systemMapping/authentication_validator.go
  validation/systemMapping/authentication_validator_test.go
  validation/systemMapping/backend_validator.go
  validation/systemMapping/backend_validator_test.go
  validation/systemMapping/protocol_list_validator.go
  validation/systemMapping/protocol_list_validator_test.go
  validation/systemMapping/protocol_validator.go
  validation/systemMapping/protocol_validator_test.go
Labels: bug, breaking-change

#122 chore: include dependencies to release notes
  .github/release.yml
Labels: ignore-for-release, internal
